title: "我的个人网站"
description: "记录个人生活与技术分享"
baseurl: ""
url: "https://yourwebsite.com"
logo: "/assets/logo.png"

theme: minima

lang: zh-CN
timezone: Asia/Shanghai
date_format: "%Y年%m月%d日"

author:
  name: "你的名字"
  avatar: "/assets/images/avatar.jpg"
  bio: "个人简介"
  location: "城市, 国家"
  email: "你的邮箱"
  links:
    - label: "GitHub"
      url: "https://github.com/你的用户名"
    - label: "Twitter"
      url: "https://twitter.com/你的用户名"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num"

jekyll-archives:
  enabled: [year, tags]
  layouts:
    year: "archive-year"
    tag: "archive-tag"
  permalinks:
    year: "/archives/:year/"
    tag: "/tags/:tag/"

share:
  twitter: true
  facebook: true
  linkedin: true

custom:
  open_graph: true
  twitter_cards: true
  github_edit:
    repository: "你的用户名/personal-website"
    branch: "main"